./import_profile.pl CIS_Microsoft_Windows_Server_2012_R2.sql
./import_profile.pl Microsoft_Windows_Server_2008_R2_ISO-27002-v1_2008.sql
./import_profile.pl Microsoft_Windows_Server_2008_R2_MAC-1_Classified_2008.sql
./import_profile.pl Microsoft_Windows_Server_2008_R2_PCI-DSS_2008.sql
./import_profile.pl Microsoft_Windows_Server_2012_R2_ISO-27002-v1_2012.sql
./import_profile.pl Microsoft_Windows_Server_2012_R2_PCI-DSS_2012.sql
./import_profile.pl Microsoft_Windows_Server_2012_R2_NPCI_CIS_Beta.sql
./import_profile.pl Santander-CIS-Windows-2012-R2_Beta.sql
./import_profile.pl Microsoft_Windows_Server_2012_MAC-1_Classified_2012_Beta.sql
./import_profile.pl Microsoft_Windows_Server_2016_MAC-1_Classified_2016_Beta.sql
./import_profile.pl CIS_Windows_2012_Std_Beta.sql
./import_profile.pl [Windows_Server]__DEMO_PROFILE.sql
./import_profile.pl [Windows_Server]__UNDO_DEMO_PROFILE.sql
./import_profile.pl [debian-based_Linux]__DEMO_PROFILE.sql
./import_profile.pl [debian-based_Linux]__MAC-1_Classified.sql
./import_profile.pl [debian-based_Linux]__MAC-1_Classified1.sql
./import_profile.pl [debian-based_Linux]__MAC-1_Classified2.sql
./import_profile.pl [debian-based_Linux]__CIS_Profile_Subset.sql
./import_profile.pl [debian-based_Linux]__CIS_Profile_Ubuntu_18_Subset.sql
./import_profile.pl [debian-based_Linux]__PCI_DSS.sql
./import_profile.pl [debian-based_Linux]__PCI_DSS1.sql
./import_profile.pl [debian-based_Linux]__PCI_for_OpenStack.sql
./import_profile.pl [debian-based_Linux]__Trusted_Boot.sql
./import_profile.pl [debian-based_Linux]__UNDO_COMPLIANCE_CHANGES.sql
./import_profile.pl [debian-based_Linux]__UNIX.sql
./import_profile.pl [rpm-based_Linux]__DEMO_PROFILE.sql
./import_profile.pl [rpm-based_Linux]__MAC-1_Classified1.sql
./import_profile.pl [rpm-based_Linux]__MAC-1_Classified2.sql
./import_profile.pl [rpm-based_Linux]__PCI_DSS.sql
./import_profile.pl [rpm-based_Linux]__PCI_DSS1.sql
./import_profile.pl [rpm-based_Linux]__CIS_Profile_Subset.sql
./import_profile.pl [rpm-based_Linux]__PCI_for_OpenStack.sql
./import_profile.pl [rpm-based_Linux]__Trusted_Boot.sql
./import_profile.pl [rpm-based_Linux]__UNDO_COMPLIANCE_CHANGES.sql
./import_profile.pl [rpm-based_Linux]__UNIX.sql
./import_profile.pl ESX_Demo_Profile.sql
./import_profile.pl SoftLayer_Management_Plane_MPlane_SoftLayer.sql
./import_profile.pl  Reference_Profile_Linux.sql
./import_profile.pl  Reference_Profile_Windows2008.sql
./import_profile.pl  Reference_Profile_Windows2012.sql
./import_profile.pl [debian-based_Linux]__Master_Profile.sql
./import_profile.pl [rpm-based_Linux]__Master_Profile.sql
./import_profile.pl Microsoft_Windows_Server_2008_R2_Master_Profile.sql
./import_profile.pl Microsoft_Windows_Server_2012_R2_Master_Profile.sql